[project]
name = "furocya-tohenkan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "graphviz>=0.21",
    "pycparser>=2.23",
    "vsdx>=0.5.19",
]
